const CART_KEY = 'miel-khadija-cart-v1';
const VISITOR_KEY = 'miel-khadija-visitor-id';
const visitorId = localStorage.getItem(VISITOR_KEY) || crypto.randomUUID();
localStorage.setItem(VISITOR_KEY, visitorId);
let cart = JSON.parse(localStorage.getItem(CART_KEY) || '[]');
document.body.insertAdjacentHTML('beforeend', `<button class="cart-toggle" aria-label="Ouvrir le panier">Panier <span>0</span></button><div class="cart-backdrop"></div><aside class="cart-drawer" aria-label="Votre panier"><header><div><small>VOTRE SÉLECTION</small><h2>Mon panier</h2></div><button class="cart-close" aria-label="Fermer">×</button></header><div class="cart-items"></div><footer><div><span>Total</span><strong class="cart-total">0 DT</strong></div><button class="cart-checkout">Commander sur WhatsApp ↗</button><small>Panier mémorisé uniquement sur cet appareil.</small></footer></aside>`);
const drawer = document.querySelector('.cart-drawer'); const backdrop = document.querySelector('.cart-backdrop');
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));renderCart()}
function openCart(open=true){drawer.classList.toggle('open',open);backdrop.classList.toggle('open',open)}
function renderCart(){const count=cart.reduce((sum,item)=>sum+item.quantity,0);document.querySelector('.cart-toggle span').textContent=count;document.querySelector('.cart-items').innerHTML=cart.length?cart.map(item=>`<article><img src="${item.image_url}" alt=""><div><h3>${item.name}</h3><p>${item.price} DT · ${item.format}</p><div class="cart-quantity"><button data-minus="${item.id}">−</button><span>${item.quantity}</span><button data-plus="${item.id}">+</button><button data-remove="${item.id}">Retirer</button></div></div></article>`).join(''):'<p class="empty-cart">Votre panier est vide.</p>';const total=cart.reduce((sum,item)=>sum+Number(item.price)*item.quantity,0);document.querySelector('.cart-total').textContent=`${total.toFixed(total%1?2:0)} DT`}
function addProduct(product){const existing=cart.find(item=>item.id===product.id);if(existing)existing.quantity+=1;else cart.push({...product,quantity:1});saveCart();openCart()}
document.addEventListener('click',event=>{const add=event.target.closest('[data-cart-product]');if(add){try{addProduct(JSON.parse(add.dataset.cartProduct))}catch{}return}const plus=event.target.closest('[data-plus]'),minus=event.target.closest('[data-minus]'),remove=event.target.closest('[data-remove]');if(plus)cart.find(item=>item.id===plus.dataset.plus).quantity++;if(minus){const item=cart.find(item=>item.id===minus.dataset.minus);if(item)item.quantity--;cart=cart.filter(item=>item.quantity>0)}if(remove)cart=cart.filter(item=>item.id!==remove.dataset.remove);if(plus||minus||remove)saveCart()});
document.querySelector('.cart-toggle').addEventListener('click',()=>openCart());document.querySelector('.cart-close').addEventListener('click',()=>openCart(false));backdrop.addEventListener('click',()=>openCart(false));
document.querySelector('.cart-checkout').addEventListener('click',()=>{if(!cart.length)return;const lines=cart.map(item=>`• ${item.name} × ${item.quantity} — ${(Number(item.price)*item.quantity).toFixed(2)} DT`);const total=cart.reduce((sum,item)=>sum+Number(item.price)*item.quantity,0).toFixed(2);const message=`Bonjour Miel Khadija, je souhaite commander :\n\n${lines.join('\n')}\n\nTotal : ${total} DT\nRéférence panier : ${visitorId.slice(0,8).toUpperCase()}\n\nPouvez-vous confirmer la disponibilité ?`;window.open(`https://wa.me/21694323527?text=${encodeURIComponent(message)}`,'_blank','noopener')});renderCart();
