const detailRoot = document.createElement('div');
detailRoot.innerHTML = `<div class="product-modal-backdrop"></div><dialog class="product-modal"><button class="product-modal-close" aria-label="Fermer">×</button><div class="product-modal-content"></div></dialog>`;
document.body.append(...detailRoot.children);
const productModal = document.querySelector('.product-modal');
const productModalBackdrop = document.querySelector('.product-modal-backdrop');
const productModalContent = document.querySelector('.product-modal-content');
function detailPrice(product){return product.is_promo&&product.promo_price?`<div class="modal-price promo"><s>${product.price} DT</s><strong>${product.promo_price} DT</strong></div>`:`<div class="modal-price"><strong>${product.price} DT</strong></div>`}
function openProductDetail(product){const salePrice=product.is_promo&&product.promo_price?product.promo_price:product.price;const cartProduct={...product,price:salePrice};const message=`Bonjour Miel Khadija, je souhaite commander ${product.name} (${product.format} - ${salePrice} DT). Pouvez-vous confirmer sa disponibilité ?`;productModalContent.innerHTML=`<figure><img src="${product.image_url}" alt="${product.name}"></figure><section dir="auto"><div class="modal-labels">${product.is_new?'<b>Nouveau</b>':''}${product.is_promo?'<b class="promo">Promo</b>':''}${product.is_featured?'<b class="featured">🔥 En vedette</b>':''}</div><small>${product.subtitle||'Miel Khadija'}</small><h2>${product.name}</h2><p class="modal-format">${product.format}</p><p class="modal-description">${product.description||'Un produit Miel Khadija préparé avec soin à Medjez El Bab.'}</p>${detailPrice(product)}<div class="modal-actions"><button class="add-cart" data-cart-product='${JSON.stringify(cartProduct).replaceAll("'","&#39;")}'>Ajouter au panier +</button><a href="https://wa.me/21694323527?text=${encodeURIComponent(message)}" target="_blank" rel="noopener">Commander sur WhatsApp ↗</a></div></section>`;productModal.showModal();productModalBackdrop.classList.add('open')}
function closeProductDetail(){productModal.close();productModalBackdrop.classList.remove('open')}
document.addEventListener('click',event=>{if(event.target.closest('button,a'))return;const card=event.target.closest('[data-product-detail]');if(card){try{openProductDetail(JSON.parse(card.dataset.productDetail))}catch{}}});
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-product-detail]')){event.preventDefault();try{openProductDetail(JSON.parse(event.target.dataset.productDetail))}catch{}}});
document.querySelector('.product-modal-close').addEventListener('click',closeProductDetail);productModalBackdrop.addEventListener('click',closeProductDetail);productModal.addEventListener('click',event=>{if(event.target===productModal)closeProductDetail()});productModal.addEventListener('close',()=>productModalBackdrop.classList.remove('open'));
